import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, MapPin, CreditCard, Wallet, Check, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Alert, AlertDescription } from '@/components/ui/alert';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { useCartContext } from '@/contexts/CartContext';
import { useAuth } from '@/contexts/AuthContext';
import { useCreateOrder } from '@/hooks/useFirebase';
import { useToast } from '@/hooks/use-toast';
import { Address } from '@/types';
import { dataProvider } from '@/lib/dataProvider';
import { Timestamp } from 'firebase/firestore';

const Checkout = () => {
  const navigate = useNavigate();
  const { cart, getSubtotal, clearCart } = useCartContext();
  const { currentUser } = useAuth();
  const { toast } = useToast();
  const createOrder = useCreateOrder();

  const [paymentMethod, setPaymentMethod] = useState('card');
  const [isProcessing, setIsProcessing] = useState(false);
  const [priceWarnings, setPriceWarnings] = useState<string[]>([]);
  
  // Address form state
  const [addressForm, setAddressForm] = useState({
    label: 'Home',
    addressLine1: '',
    addressLine2: '',
    city: '',
    state: '',
    pincode: '',
  });

  const subtotal = getSubtotal();
  const deliveryFee = 40;
  const tax = subtotal * 0.08;
  const total = subtotal + deliveryFee + tax;

  // Validate prices at checkout
  useEffect(() => {
    const validatePrices = async () => {
      if (!cart.restaurantId) return;

      try {
        const currentMenuItems = await dataProvider.getMenuByRestaurantId(cart.restaurantId);
        const warnings: string[] = [];

        cart.items.forEach(cartItem => {
          const currentItem = currentMenuItems.find(item => item.id === cartItem.menuItem.id);
          
          if (!currentItem) {
            warnings.push(`${cartItem.menuItem.name} is no longer available`);
          } else if (currentItem.price !== cartItem.menuItem.price) {
            warnings.push(
              `Price of ${cartItem.menuItem.name} has changed from ₹${cartItem.menuItem.price.toFixed(0)} to ₹${currentItem.price.toFixed(0)}`
            );
          }
        });

        setPriceWarnings(warnings);
      } catch (error) {
        console.error('Error validating prices:', error);
      }
    };

    validatePrices();
  }, [cart]);

  // Redirect if cart is empty
  if (cart.items.length === 0) {
    navigate('/cart');
    return null;
  }

  const handleAddressChange = (field: string, value: string) => {
    setAddressForm(prev => ({ ...prev, [field]: value }));
  };

  const validateForm = () => {
    if (!addressForm.addressLine1 || !addressForm.city || !addressForm.state || !addressForm.pincode) {
      toast({
        title: 'Error',
        description: 'Please fill in all required address fields',
        variant: 'destructive',
      });
      return false;
    }

    if (addressForm.pincode.length !== 6 || !/^\d+$/.test(addressForm.pincode)) {
      toast({
        title: 'Error',
        description: 'Please enter a valid 6-digit pincode',
        variant: 'destructive',
      });
      return false;
    }

    return true;
  };

  const handlePlaceOrder = async () => {
    if (!validateForm()) return;

    // Check for price warnings and block submission
    if (priceWarnings.length > 0) {
      toast({
        title: 'Price Changes Detected',
        description: 'Some items have price changes. Please return to cart to update.',
        variant: 'destructive',
      });
      return;
    }

    setIsProcessing(true);

    try {
      const deliveryAddress: Address = {
        id: '', // Will be generated by Firebase
        userId: currentUser.uid,
        ...addressForm,
        isDefault: false,
      };

      // Get current time and add 45 minutes for estimated delivery
      const now = new Date();
      const estimatedDelivery = new Date(now.getTime() + 45 * 60000);

      const orderData = {
        userId: currentUser.uid,
        restaurantId: cart.restaurantId!,
        restaurantName: cart.restaurantName!,
        items: cart.items,
        totalAmount: total,
        deliveryFee,
        status: 'placed' as const,
        paymentStatus: paymentMethod === 'cod' ? 'pending' as const : 'paid' as const,
        deliveryAddress,
        estimatedDelivery: Timestamp.fromDate(estimatedDelivery),
      };

      const orderId = await createOrder.mutateAsync(orderData);

      // Clear cart
      clearCart();

      // Navigate to order confirmation with order data
      navigate('/order-confirmation', {
        state: {
          orderId,
          restaurantName: cart.restaurantName,
          total: total.toFixed(0),
          paymentMethod: paymentMethod === 'card' ? 'Credit/Debit Card' : paymentMethod === 'upi' ? 'UPI' : 'Cash on Delivery',
          address: `${addressForm.addressLine1}, ${addressForm.city}, ${addressForm.state} - ${addressForm.pincode}`,
        },
      });
    } catch (error) {
      console.error('Order creation error:', error);
      if (error instanceof Error) {
        toast({
          title: 'Error',
          description: error.message,
          variant: 'destructive',
        });
      } else {
        toast({
          title: 'Error',
          description: 'Failed to place order. Please try again.',
          variant: 'destructive',
        });
      }
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      <main className="flex-1 py-8">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Header */}
          <div className="flex items-center gap-4 mb-8">
            <Link to="/cart">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold">Checkout</h1>
              <p className="text-muted-foreground">Complete your order</p>
            </div>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Checkout Form */}
            <div className="lg:col-span-2 space-y-6">
              {/* Price warnings */}
              {priceWarnings.length > 0 && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    <p className="font-semibold mb-2">Price changes detected:</p>
                    <ul className="list-disc list-inside space-y-1">
                      {priceWarnings.map((warning, index) => (
                        <li key={index} className="text-sm">{warning}</li>
                      ))}
                    </ul>
                    <p className="mt-2 text-sm">Please return to cart to update your order.</p>
                  </AlertDescription>
                </Alert>
              )}

              {/* Delivery Address */}
              <div className="bg-card rounded-2xl shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <MapPin className="w-5 h-5 text-primary" />
                  <h2 className="text-lg font-bold">Delivery Address</h2>
                </div>

                <div className="space-y-4">
                  <div>
                    <Label htmlFor="label">Address Label</Label>
                    <Input
                      id="label"
                      placeholder="Home, Work, etc."
                      value={addressForm.label}
                      onChange={(e) => handleAddressChange('label', e.target.value)}
                    />
                  </div>

                  <div>
                    <Label htmlFor="addressLine1">Address Line 1 *</Label>
                    <Input
                      id="addressLine1"
                      placeholder="House/Flat No., Building Name"
                      value={addressForm.addressLine1}
                      onChange={(e) => handleAddressChange('addressLine1', e.target.value)}
                      required
                    />
                  </div>

                  <div>
                    <Label htmlFor="addressLine2">Address Line 2</Label>
                    <Input
                      id="addressLine2"
                      placeholder="Street, Area, Landmark"
                      value={addressForm.addressLine2}
                      onChange={(e) => handleAddressChange('addressLine2', e.target.value)}
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="city">City *</Label>
                      <Input
                        id="city"
                        placeholder="City"
                        value={addressForm.city}
                        onChange={(e) => handleAddressChange('city', e.target.value)}
                        required
                      />
                    </div>
                    <div>
                      <Label htmlFor="state">State *</Label>
                      <Input
                        id="state"
                        placeholder="State"
                        value={addressForm.state}
                        onChange={(e) => handleAddressChange('state', e.target.value)}
                        required
                      />
                    </div>
                  </div>

                  <div>
                    <Label htmlFor="pincode">Pincode *</Label>
                    <Input
                      id="pincode"
                      placeholder="6-digit pincode"
                      value={addressForm.pincode}
                      onChange={(e) => handleAddressChange('pincode', e.target.value)}
                      maxLength={6}
                      required
                    />
                  </div>
                </div>
              </div>

              {/* Payment Method */}
              <div className="bg-card rounded-2xl shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <CreditCard className="w-5 h-5 text-primary" />
                  <h2 className="text-lg font-bold">Payment Method</h2>
                </div>

                <RadioGroup value={paymentMethod} onValueChange={setPaymentMethod}>
                  <div className="space-y-3">
                    <div className="flex items-center space-x-3 p-4 border rounded-lg cursor-pointer hover:bg-muted/50 transition-colors">
                      <RadioGroupItem value="card" id="card" />
                      <Label htmlFor="card" className="flex-1 cursor-pointer">
                        <div className="flex items-center gap-2">
                          <CreditCard className="w-5 h-5" />
                          <div>
                            <p className="font-medium">Credit / Debit Card</p>
                            <p className="text-sm text-muted-foreground">Pay securely with your card</p>
                          </div>
                        </div>
                      </Label>
                    </div>

                    <div className="flex items-center space-x-3 p-4 border rounded-lg cursor-pointer hover:bg-muted/50 transition-colors">
                      <RadioGroupItem value="upi" id="upi" />
                      <Label htmlFor="upi" className="flex-1 cursor-pointer">
                        <div className="flex items-center gap-2">
                          <Wallet className="w-5 h-5" />
                          <div>
                            <p className="font-medium">UPI</p>
                            <p className="text-sm text-muted-foreground">Pay using UPI apps</p>
                          </div>
                        </div>
                      </Label>
                    </div>

                    <div className="flex items-center space-x-3 p-4 border rounded-lg cursor-pointer hover:bg-muted/50 transition-colors">
                      <RadioGroupItem value="cod" id="cod" />
                      <Label htmlFor="cod" className="flex-1 cursor-pointer">
                        <div className="flex items-center gap-2">
                          <Wallet className="w-5 h-5" />
                          <div>
                            <p className="font-medium">Cash on Delivery</p>
                            <p className="text-sm text-muted-foreground">Pay when you receive</p>
                          </div>
                        </div>
                      </Label>
                    </div>
                  </div>
                </RadioGroup>
              </div>
            </div>

            {/* Order Summary */}
            <div className="lg:col-span-1">
              <div className="bg-card rounded-2xl shadow-card p-6 sticky top-24">
                <h2 className="text-lg font-bold mb-4">Order Summary</h2>

                {/* Restaurant Info */}
                <div className="mb-4 pb-4 border-b">
                  <p className="font-medium">{cart.restaurantName}</p>
                  <p className="text-sm text-muted-foreground">
                    {cart.items.length} item{cart.items.length > 1 ? 's' : ''}
                  </p>
                </div>

                {/* Order Items */}
                <div className="space-y-2 mb-4 pb-4 border-b max-h-48 overflow-y-auto">
                  {cart.items.map((item) => (
                    <div key={item.menuItem.id} className="flex justify-between text-sm">
                      <span className="text-muted-foreground">
                        {item.menuItem.name} × {item.quantity}
                      </span>
                      <span className="font-medium">
                        ₹{(item.menuItem.price * item.quantity).toFixed(0)}
                      </span>
                    </div>
                  ))}
                </div>

                {/* Price Breakdown */}
                <div className="space-y-3 text-sm mb-4">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Subtotal</span>
                    <span className="font-medium">₹{subtotal.toFixed(0)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Delivery Fee</span>
                    <span className="font-medium">₹{deliveryFee.toFixed(0)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Tax (GST)</span>
                    <span className="font-medium">₹{tax.toFixed(0)}</span>
                  </div>

                  <div className="border-t pt-3">
                    <div className="flex justify-between text-lg font-bold">
                      <span>Total</span>
                      <span>₹{total.toFixed(0)}</span>
                    </div>
                  </div>
                </div>

                <Button
                  variant="hero"
                  size="lg"
                  className="w-full"
                  onClick={handlePlaceOrder}
                  disabled={isProcessing}
                >
                  {isProcessing ? (
                    'Processing...'
                  ) : (
                    <>
                      <Check className="w-4 h-4 mr-2" />
                      Place Order
                    </>
                  )}
                </Button>

                <p className="text-xs text-muted-foreground text-center mt-4">
                  By placing your order, you agree to our Terms of Service and Privacy Policy
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Checkout;
